[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npx vite --port 5173"
  port = 8888
  targetPort = 5173
  publish = "dist"
  framework = "#auto"
  autoLaunch = false
  functions = "netlify/functions"

[[redirects]]
  from = "/users/:uid/blogs/:blogId/api/content.json"
  to = "/.netlify/functions/content-api?uid=:uid&blogId=:blogId"
  status = 200

[[redirects]]
  from = "/users/:uid/blogs/:blogId/api/products.json"
  to = "/.netlify/functions/product-api?uid=:uid&blogId=:blogId"
  status = 200

[[redirects]]
  from = "/api/admin/content"
  to = "/.netlify/functions/admin-content"
  status = 200

[[redirects]]
  from = "/api/admin/products"
  to = "/.netlify/functions/admin-product"
  status = 200

[[redirects]]
  from = "/api/admin/users"
  to = "/.netlify/functions/admin-users"
  status = 200

[[redirects]]
  from = "/api/admin/blog"
  to = "/.netlify/functions/admin-blog"
  status = 200

[[redirects]]
  from = "/api/import/content"
  to = "/.netlify/functions/import-content"
  status = 200

[[redirects]]
  from = "/api/import/products"
  to = "/.netlify/functions/import-products"
  status = 200

[[redirects]]
  from = "/api/export/content"
  to = "/.netlify/functions/export-content"
  status = 200

[[redirects]]
  from = "/api/export/products"
  to = "/.netlify/functions/export-products"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
